### PR TITLE
Add docstrings

### PR DESCRIPTION
**Pull request by willingc**
@parente While debugging some of the Travis stuff, I added some docstrings while reading these files.

### CODE REVIEW

**Comment by parente** [comment]
Thanks @willingc . I think you did the same files I did last night over in PR #109 though. :/

**Comment by willingc** [comment]
@parente Lol. No worries since I did it while troubleshooting Travis. I've gotten Travis to run all the tests without timing out. Now I have to figure out why some of the tests are failing.

**Comment by parente** [comment]
Going to close this in favor of the other which includes these and more.

**Comment by willingc** [comment]
Absolutely. Thanks @parente. On another note, I think I isolated two places in jupyter_client that may be causing the Runtime Errors in Travis.

**Pull request closed without merging**
