### PR TITLE
Concatenate cells with repeat annotations

### PR DESCRIPTION
**Pull request by parente**
Support typical notebook development: lots of small cells, no need to join.

This is for notebook-http mode.

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
Do we want to include a system test with a notebook with multiple annotated cells?

**Comment by parente** [comment]
Sure. Can if you think the unit test is not enough.

**Comment by parente** [comment]
System test added. Cleaned up the test notebooks a bit too.

**Comment by Lull3rSkat3r** [comment]
LGTM :shipit: :pig:

**Pull request merged**
